services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-image-processor
    restart: unless-stopped
    ports:
      - "6060:3000"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS="--max-old-space-size=4096"
      - NEXT_PUBLIC_DEBUG=true  # Set to 'true' to enable debug logging
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/healthcheck || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
