services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_DEBUG=${NEXT_PUBLIC_DEBUG}
    container_name: nextjs-image-processor
    restart: unless-stopped
    ports:
      - "6060:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - NODE_OPTIONS=${NODE_OPTIONS}
      - NEXT_PUBLIC_DEBUG=${NEXT_PUBLIC_DEBUG}
      - HOSTNAME=${HOSTNAME}
      - NEXT_PUBLIC_SITE_NAME=${NEXT_PUBLIC_SITE_NAME}
      - NEXT_PUBLIC_SITE_DESCRIPTION=${NEXT_PUBLIC_SITE_DESCRIPTION}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
      - NEXT_PUBLIC_SITE_THEME_COLOR=${NEXT_PUBLIC_SITE_THEME_COLOR}
      - NEXT_PUBLIC_SITE_BACKGROUND_COLOR=${NEXT_PUBLIC_SITE_BACKGROUND_COLOR}
    volumes:
      - ./custom-icons:/app/public/custom-icons
    healthcheck:
      test: ["CMD-SHELL", "echo 'Debug setting:' $NEXT_PUBLIC_DEBUG && curl -f http://localhost:3000/api/healthcheck || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
