name: Simple Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Run simple test
        run: pnpm test -- __tests__/simple.test.js --no-cache

      - name: Run API tests
        run: NODE_ENV=test-node pnpm test -- __tests__/api/healthcheck.test.js __tests__/api/cleanup.test.js --no-cache
        env:
          CLEANUP_API_KEY: "test-api-key-for-ci"

      - name: Run utility tests
        run: NODE_ENV=test-node pnpm test -- __tests__/utils/cleanup.test.js __tests__/utils/rate-limit.test.js --no-cache
        env:
          CLEANUP_API_KEY: "test-api-key-for-ci"
